[versions]
record-args = "0.9.3"
junit-jupiter = "5.14.2"

[libraries]
record-args = { module = "dev.nipafx.args:record-args", version.ref = "record-args" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
